en:
  languageName: English
  weight: 1
  params:
    description: Heloo under world.
    keywords: 'hugo, tech, engineer, Python'

ja:
  languageName: 日本語
  weight: 2
  params:
    description: Heloo under world.
    keywords: 'hugo, tech, engineer, Python'
    archive:
      dateFormat: "01-02"

zh-hans:
  languageName: 简体中文
  weight: 4
  params:
    description: Heloo under world.
    keywords: 'hugo, tech, engineer, Python'
    archive:
      dateFormat: 01-02
