# Sass トランスパイラを Dart Sass に切り替える場合は以下をアンコメントしてください
# sass_transpiler: 'dartsass'

# メインセクションの定義
mainSections:
  - blog
  - posts
  - news

# タイトルの区切り文字（デフォルトは '-'）
# titleSeparator: '|'

# サイトの説明
description: "Heloo under world."

# サイトのキーワード
keywords: "hugo, tech, engineer, Python"

# images：
# - site-feature-image.jpg

# metaRobots: noindex, nofollow # metaタグのRobotsのデフォルト値
# metaRobots：  # metaタグのRobotsを無効にする

# logo: images/logo.png # ロゴ画像。デフォルトはimages/logo.webp。
# logo: false # ロゴを無効にする

# サイトのブランド名
brand: Boochi-Engineer

# カラーパレット
palette: blue-gray # デフォルトのパレット。オプションのパレットへ変更後はブラウザのキャッシュをクリアする必要があります.
# 利用可能なpalette. デフォルトはALL. 空の配列は無効を意味する.
# palette：
#  - blue
#  - blue-gray
#  - brown
#  - cyan
#  - green
#  - indigo
#  - orange
#  - pink
#  - purple
#  - red
#  - teal
#  - yellow

# color: dark # light, dark or auto. デフォルトは auto。

# fullWidth: true # 全幅.
# fixedHeader: false # 固定ヘッダの表示/非表示を切り替える.

# 日付フォーマット
dateFormat: ":date_long"

# Google Adsense の設定
googleAdsense: 

# math: true # 全世界で数学を有効にする.
# toc: false # TOC をグローバルに無効にする.
# tocPosition: content
# breadcrumb: false # パンくずを無効にする
# breadcrumbDivider： > パンくずを分割する
# ダイアグラム: true
# socialShare: false # SNS共有を無効にする
# searchBar: false # 検索バーを無効にする

# poweredBy: false # パワードバイを表示するかどうか。

# readingTime: false # 読書時間を表示するかどうか。
# postDate: false # 投稿メタセクションに投稿日時を表示するかどうか.

# featuredPostCount： 10 # サイドバーに表示される特集記事の数. falseに設定することでオフにできる.
# recentPostCount： 10 # サイドバーに表示される最近の投稿の数. falseに設定することでオフにできる.
# relatedPostCount： 10 # 関連する投稿の数. falseに設定してオフにする.
# categoryCount： 10 # サイドバーに表示されるカテゴリの数. falseに設定することでオフにできる.
# tagCount： 10 # サイドバーに表示されるタグの数. falseに設定することでオフにできる.
# seriesCount： 20 # サイドバーに表示されるシリーズの数. falseに設定することでオフにできる.
# taxonomyPaginate： 5 # デフォルトは10.

# taxonomyの投稿数。falseに設定することでオフにできる。
taxonomyPostCount: 20

# taxonomyの投稿数をカウントする。
countTaxonomyPosts: true 

# サイドバーのtaxonomyの並び順。
# sidebarTaxonomies: [categories, tags, series]  

# ピン留め投稿のオン/オフ。
# pinnedPost: false 

# ピン留めされた投稿の数。
pinnedPostCount: 3 

# Custom CSS と JS
customCSS:
customJS:

# 投稿の単語数がこの値を超えた場合のみTOC（目次）が表示される。
tocWordCount: 1 

# 大文字のタイトル。
titleCase: true 

# 画像ビューア
viewer: true 

# backgroundImage: ['/images/bg-light.png', '/images/bg-dark.png']

# RSSボタンをホームページに常時リンクする。
# rss: home 

# サイドバーの設定
sidebar:
  fixed: true
  # アーカイブウィジェットを有効にする
  # archives: true

  # タクソノミートグルを無効にする
  # taxonomiesToggle: false

  # カテゴリウィジェットを有効にする
  # categories: true

  # タグウィジェットを有効にする
  # tags: true

  # シリーズウィジェットを有効にする
  # series: true

  # 著者ウィジェットを有効にする
  # authors: true

  # 投稿ウィジェットを無効にする
  # postsToggle: false

  # 特集記事ウィジェットを有効にする
  # featuredPosts: true

  # 特集記事ウィジェットを有効にする
  # recentPosts: true

  # 小さな画面ではデフォルトでサイドバーウィジェットを折りたたむ。
  # collapsed: true

# コードブロックの設定
codeBlock:
  # 最大行数: 8
  # 行番号の表示/非表示
  lineNos: true

# 投稿設定
post:
  # 抜粋：説明
  # excerptMaxLength: 120
  # copyright: false # 各投稿にコピーライトセクションを表示するかどうか.
  # plainifyExcerpt: false # falseの場合、抜粋をHTMLで整形する。

  # 特集画像をコンテンツの上に表示する。
  featuredImage: true

  # 見出しに番号を付ける。
  numberifyHeadings: true

  # 数える見出しの深さ. デフォルトは6です。
  # numberifyHeadingsEndLevel: 4

  # 見出し番号の区切り文字
  numberifyHeadingsSeparator: .
  # TOCのCSS list-style-typeプロパティ。
  # tocStyleType: decimal

  # imageTitleAsCaption: true
  
  # 投稿パネルを無効にする
  # panel: false

  # ポストナビゲーションを無効にする。
  # nav: false

  # 続きを読むボタンをクリックした後のページ位置. デフォルトはページの先頭です.
  # この機能は, <!-more-->で分割された手動要約のみをサポートします.
  # readMoreFromContent: true

# アーカイブ設定
archive:
  paginate: 20 
  # アーカイブのページネーション。デフォルトは100。
  # basePath = 「/archiv」. # アーカイブページのベースパス.
  # dateFormat： 01-02 # アーカイブの日付フォーマット. デフォルトは1月2日.

analytics:
  google: null
  baidu: null

# Site verification
siteVerification:
  google: 
  bing: 
  baidu: 
  baiduUnion:  # Baidu Union
  so: 
  sogou: 
  shenma: 

# Creative Commons ライセンス設定
creativeCommons: null
  # by: true # 創作者であるあなたへのクレジット表記が必要です。
  # nc: true # あなたの作品の非商用利用のみが許可されます.
  # nd: true # あなたの作品の派生物や翻案物の利用は許可されません.
  # sa: true # 翻案も同じ条件で共有されなければならない.

# utterances:
  # あなたのリポジトリに置き換えてください。
  # repo: Siro-Yamaneko/siro-yamaneko.github.io
  #issueTerm: pathname # pathname, url, title, og:title
  # label: comment
  # デフォルトでは、ライトモードはgithub-light、ダークモードはgithub-darkに対応します。
  # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
  #theme:  

#staticman:
  #endpoint: https://yourstaticmaninstance # Required, replace with your own Staticman instance.
  #repo: user/repo # Required
  #service: github # or gitlab. Default to GitHub.
  #branch: main # Default to master.
  #property: comments # Default to comments.
  #sorting: desc # Default to asc.
  #reCaptchaKey: "" # The reCaptcha site key.
  #reCaptchaSecret: "" # The reCaptcha encrypted secret. You'll need to encrypt plain secret via https://yourstaticmaninstance/v3/encrypt/PLAINSECRET.
  #extraFields: # Extra fields. Available fiedls: url.
  #  - url
  #requiredFields: # Extra required fields. Available fields: email and the extra fields.
  #  - email
  #  - url
  #paginate: 5 # Default to 10.
  #moderation: false # Same as Staticman's moderation.

# コメントシステム (Giscus) の設定
# See https://giscus.app
giscus:
  repo: "razonyang/hugo-theme-bootstrap-skeleton" # required.
  repoId: "R_kgDOHJi95g" # required.
  category: "General" # required.
  categoryId: "DIC_kwDOHJi95s4CTy6q" # required.
  # theme: "dark" # Default to auto.
  # mapping: "title" # Default to pathname.
  # inputPosition: "bottom" # Default to top.
  # reactions: false # Disable reactions.
  # metadata: true # Emit discussion metadata.
  # lang: "en" # Specify language, default to site language.
  # lazyLoading: false # Default to true.


# サイト内検索の設定
search:
  # ページネーション。デフォルトは 10。
  paginate: 5
  # 結果を表示する際の最大ワード数
  # resultContentWordCount: 240 
  
  #  Fuse.jsのオプション。 https://fusejs.io/api/options.html を参照してください.
  fuse:
    # ignoreLocation: true
    # location: 0
    # isCaseSensitive: false
    # minMatchCharLength: 1
    threshold: 0.1
    # distance: 100
    # useExtendedSearch: true

#docsearch:
  # https://docsearch.algolia.com/docs/api
  # container: ".search-bar" # replace it if necessary, default to '.search-bar'.
  # appId: ""
  # apiKey: ""
  # indexName: ""
  # debug: true

# 報酬用のQRコード画像
reward:
  alipay: images/reward/alipay.png
  wechat: images/reward/wechat.png
  #paypal: images/reward/paypal.png
  #patreon: images/reward/patreon.png
  #liberapay: images/reward/liberapay.png

#share:
  #addThis:  # AddThis pubid.

# 報酬用のQRコード画像
#actionsPanel:
  # disabled: true

# フォントサイズ設定
# フォントサイズスイッチャーを無効にするには, この設定をコメントまたは削除してください。
fontSize:
  # extraSmall: .8rem
  # small: .9rem
  # large: 1.1rem
  # extraLarge: 1.2rem

# プログレッシブウェブアプリ（PWA）の設定
pwa:
  manifest:
    # name:  # Default to site title.
    short_name: HBS
    # display: fullscreen # Default to standalone.
    # description:  # Default to site description.
    # theme_color: 
    # background_color: 

    # Icons
    # [[pwa.manifest.icons]]
    #   sizes: 96x96
    #   src: /images/icons/icon-96x96.png
    # [[pwa.manifest.icons]]
    #   sizes: 144x144
    #   src: /images/icons/icon-144x144.png

# お問い合わせフォームの設定
contact:
  # Netlify を使っている場合は、この行を削除してください。
  endpoint: https://getform.io/f/56041c81-9e03-4c24-b9c5-61238854d4cd
  # file: true # Enable file upload
  # fileField: image # The name of file field.
  # reCaptcha:
    # siteKey: ""

# GitHub リポジトリの設定
repo:
  url: https://github.com/razonyang/hugo-theme-bootstrap-skeleton
  branch: main
  # subPath: exampleSite
  # dateFormat: 02/01/2006, 15:04:05 PM

# トップアプリバーのソーシャルリンク
topAppBar:
  # See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
  social:
    github: razonyang/hugo-theme-bootstrap
    patreon: razonyang
    paypal: razonyang

# ドキュメントナビゲーション設定
docs:
  nav:
    expand: false # Expand docs navigation.
    reduceFontSize: true # Reduce font size of children navigation.

#feeds:
  # content: true

# ソーシャルメディアリンク
social:
  # See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
  email: user@domain.tld
  facebook: yourfacebookusername
  github: razonyang/hugo-theme-bootstrap
  gitlab: yourgitlabusername
  linkedin: yourlinkedinusername
  xing: yourxingusername
  stackoverflow: yourstackoverflowuserid
  twitter: yourtwitterusername
  weibo: yourweibousername
  zhihu: yourzhihuusername
  instagram: yourinstagramusername
  quora: yourquorausername
  tumblr: yourtumblrusername
  reddit: yourredditusername
  telegram: yourtelegramusername
  qq: yourqqnumber
  dockerhub: yourdockerhubusername
  bitbucket: yourbitbucketworkspaceid
  kaggle: yourkaggleusername
  medium: yourmediumusername # Medium username or custom domain(e.g. https://custom.domain.tld).
  lastfm: yourlastfmusername
  bilibili: yourbilibiliuserid
  youtube: youryoutubechannelid
  discord: yourdiscordinvitecode
  discourse: https://yourforum.tld
  facebookgroup: yourfacebookgroupname
  tiktok: yourtiktokusername
  pinterest: yourpinterestusername
  mastodon: yourmastodonusername
  liberapay: yourliberapayaccount
  paypal: razonyang
  patreon: razonyang
  tipeee: yourtipeeeaccount-fr


# プロフィール情報
author:
  name: '山猫シロ'
  # avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
  bio: '元SIer。現在はフリーランスのエンジニア&イラストレーター。趣味や業務で使った技術の備忘録・雑記を投稿。'

  # HTML markupがサポートされています。: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
  company: freeLance

  # HTML markupがサポートされています。: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
  location: Japan 

  # about: https://razonyang.com # The external about page. The internal about page will be used if not set.
  params: {
    # layout: compact
  }

  # See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
  social:
    email: ""
    github: Siro-Yamaneko/siro-yamaneko.github.io
    twitter: Siro_artemis
    patreon: ""
    paypal: ""
    rss: "" # Remove RSS
